[package]
name = "io"
version = "0.1.0"
authors = ["Connor <chorman64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.111",optional=true}